"""empty message

Revision ID: 46f79a4942df
Revises: e6131a34ad8d
Create Date: 2025-02-27 23:16:57.934945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46f79a4942df'
down_revision = 'e6131a34ad8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ativos', schema=None) as batch_op:
        batch_op.drop_column('senha')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ativos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha', sa.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
